### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [ricardo-aires/SEBC#1]
Your setup looks good so far. If you have not already invited `rsiwicki` as a Collaborator, please do so.

Once he has accepted, you may remove the `incomplete` label from this Issue and close it.

Good luck this week!

**Comment by ricardo-aires** [comment]
- [x] Invited `rsiwicki` as a Collaborator
- [x] `rsiwicki` accepted request to join

**Comment by ricardo-aires** [comment]
All tasks finished.
