### ISSUE TITLE
Evaluation: Full Pass

### ISSUE THREAD

**Issue by mfernest** [ricardo-aires/SEBC#15]
Based on the labs and challenge work submitted, I am pleased to offer you a Full Pass. Congratulations!

You will receive an email notification when all the work submitted for the Madrid class has been processed.

Thank you for your hard work and diligence throughout the class.

**Comment by ricardo-aires** [comment]
Thank you. It was a pleasure and really a very insightful week that helped me strength my knowledge. Cheers
