### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by ricardo-aires** [ricardo-aires/SEBC#2]
# CM Install Lab

- [x] System Configuration Checks
- [x] Configure MySQL with a replica server
- [x] CM/CDH Install Lab
- [x] Create a local parcel repo (manual) (BONUS)

**Comment by ricardo-aires** [comment]
The three mandatory tasks are done.

**Comment by ricardo-aires** [comment]
All tasks done. Submitted.

**Comment by rsiwicki** [comment]
Looks good ricard bravo
